services:
  - type: web
    name: parcour-admin-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "docker build -t parcour-admin-api ."
    startCommand: "docker run -p 8000:8000 parcour-admin-api"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: PORT
        value: "8000"
